version: '3.8'

services:
  inference:
    build:
      context: .
      dockerfile: Dockerfile.jetson
    container_name: homepi-inference
    runtime: nvidia
    ports:
      - "5001:5001"
    volumes:
      - inference-cache:/root/.cache
    shm_size: '2gb'
    ipc: host
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  inference-cache:

